In [1]:
import numpy as np

In [10]:
num_layers = 4
weight_scale = 0.01
input_dim = 2
hidden_dims = [2,3,4]
num_classes = 5

params = {}

for i in xrange(num_layers-1):
    weight_name = 'W' + str(i+1)
    bias_name = 'b' + str(i+1)
    if i==0:
        params[weight_name] = np.random.randn(input_dim,hidden_dims[i])*weight_scale
    else:
        params[weight_name] = np.random.randn(hidden_dims[i-1],hidden_dims[i])*weight_scale
    params[bias_name] = np.zeros((hidden_dims[i],))
        
#Initializing the weights and biases for the softmax/svm layer at the end
weight_name = 'W' + str(num_layers)
print weight_name
bias_name = 'b' + str(num_layers)
params[weight_name] = np.random.randn(hidden_dims[-1],num_classes)*weight_scale 
params[bias_name] = np.zeros((num_classes,))

for p in params:
    print p
    #print w


W4
W1
b4
W4
W3
b1
b2
b3
W2


In [10]:
from keras.preprocessing.image import ImageDataGenerator
a1 = np.array([[12, 2, 13, 24, 35] , [2, 7, 9 ,3, 4], [2, 2, 3, 4, 5], [22, 17, 9 ,34, 54]])
a2 = np.array([1.1, 2.3, 5.2, 3.4])
print np.random.rand(a1.shape)

ImportError: No module named keras.preprocessing.image

In [6]:
a = np.array([[12, 2, 13, 24, 35] , [2, 7, 9 ,3, 4], [2, 2, 3, 4, 5], [22, 17, 9 ,34, 54]])
print a.shape
print np.max(a,axis=0)
print np.max(a,axis=1)
print np.max(a,axis=(0,1))

(4L, 5L)
[22 17 13 34 54]
[35  9  5 54]
54


In [3]:
a = np.array([1.1, 2.3, 5.2, 3.4])
print (1/a)
print a.shape
xx = np.array_split(a,4)
print xx
yy = np.delete(xx,2,0)
print yy
zz = np.hstack(yy)
print zz
print zz.shape

[ 0.90909091  0.43478261  0.19230769  0.29411765]
(4L,)
[array([ 1.1]), array([ 2.3]), array([ 5.2]), array([ 3.4])]
[[ 1.1]
 [ 2.3]
 [ 3.4]]
[ 1.1  2.3  3.4]
(3L,)


In [15]:
#np.random.uniform(10e-5,10e-3)
print 10e-3

0.01


In [17]:
a = []
for i in xrange(5):
    a.append(i)
print a[2]

2


In [58]:
aa = np.array([1, 2, 3, 4, 5])
print  np.sqrt(np.sum(np.square(aa - a)))
print np.sum(np.square(a-aa),axis=1)


39.8120584748
[1521   64]
